# Generated by Django 3.2.10 on 2023-01-05 09:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20230105_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='call_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
