# Generated by Django 3.2.10 on 2023-01-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20230105_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='call_date',
        ),
    ]
