# Generated by Django 3.2.10 on 2023-01-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_remove_ticket_call_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
    ]
