# Generated by Django 3.2.10 on 2023-01-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_auto_20230105_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='submitter_email',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_of_problem',
            field=models.IntegerField(choices=[(1, 'MMU'), (2, 'Website'), (3, 'Treatment'), (4, 'Other')], default=4),
        ),
    ]
