# Generated by Django 3.2.10 on 2023-01-20 11:23

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_alter_ticket_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NidanTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_number', models.CharField(max_length=20, null=True)),
                ('citizen_name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('address', models.TextField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('district_name', models.CharField(max_length=100, null=True)),
                ('municipality', models.CharField(max_length=150, null=True)),
                ('colony_name', models.CharField(max_length=200, null=True)),
                ('house_number', models.CharField(max_length=40, null=True)),
                ('street_test', models.CharField(max_length=200, null=True)),
                ('section', models.CharField(max_length=150, null=True)),
                ('message', models.TextField(null=True)),
                ('subsection', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('Panding', 'Panding'), ('Solved', 'Solved')], max_length=100, null=True)),
                ('grievance_remark', models.CharField(max_length=500, null=True)),
                ('callstart', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='ProfilePicture/%y/%m/%d')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, region='IN'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assign_to',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tool.operator'),
            preserve_default=False,
        ),
    ]
