# Generated by Django 3.2.10 on 2023-01-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_auto_20230120_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assign_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.operator'),
        ),
    ]
