# Generated by Django 3.2.10 on 2023-01-20 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_alter_ticket_assign_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.operator'),
        ),
    ]
