# Generated by Django 3.2.10 on 2023-01-31 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0011_operator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assign_to',
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.operator'),
        ),
    ]
