# Generated by Django 3.2.10 on 2023-02-04 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0012_auto_20230131_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='nidanticket',
            name='opuserid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.operator'),
        ),
    ]
