# Generated by Django 3.2.10 on 2023-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0013_auto_20230204_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nidanticket',
            name='docket_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
