# Generated by Django 3.2.10 on 2023-02-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0016_auto_20230208_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nidanticket',
            name='colony_name',
        ),
        migrations.RemoveField(
            model_name='nidanticket',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='nidanticket',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='nidanticket',
            name='opuserid',
        ),
    ]
