# Generated by Django 3.2.10 on 2023-02-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0017_auto_20230209_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nidanticket',
            name='street_test',
        ),
    ]
