# Generated by Django 3.2.10 on 2023-02-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0019_auto_20230211_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='on_hold',
        ),
    ]
