# Generated by Django 3.2.10 on 2023-03-02 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tool', '0021_auto_20230225_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AreaProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='ProfilePicture/%y/%m/%d')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region='IN')),
                ('address', models.TextField(blank=True, null=True)),
                ('MMU_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_APM', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.AddIndex(
            model_name='areaprojectmanager',
            index=models.Index(fields=['date_created'], name='tool_areapr_date_cr_c4f61b_idx'),
        ),
    ]
