# Generated by Django 3.2.10 on 2023-05-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0022_auto_20230302_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low'), ('Very Low', 'Very Low')], default='Normal'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[('Open', 'Open'), ('Reopened', 'Reopened'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Duplicate', 'Duplicate')], default='Open'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_of_problem',
            field=models.IntegerField(choices=[('MMU', 'MMU'), ('Website', 'Website'), ('Treatment', 'Treatment'), ('Other', 'Other')], default='Other'),
        ),
    ]
