# Generated by Django 3.2.10 on 2023-05-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0023_auto_20230525_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[('Open', 'Open'), ('Reopened', 'Reopened'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open'),
        ),
    ]
