# Generated by Django 3.2.10 on 2023-05-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0025_auto_20230525_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_of_problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tool.typeofproblem'),
        ),
    ]
