# Generated by Django 3.2.10 on 2023-05-29 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0028_rename_first_name_ticket_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_of_problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.typeofproblem'),
        ),
    ]
